# Generated by Django 5.1.7 on 2025-03-09 13:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('text', models.TextField(verbose_name='내용')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성일')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='게시일')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/%Y/%m/%d/', verbose_name='이미지')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '게시글',
                'verbose_name_plural': '게시글',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200, verbose_name='작성자')),
                ('text', models.TextField(verbose_name='내용')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성일')),
                ('approved_comment', models.BooleanField(default=False, verbose_name='승인 여부')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post', verbose_name='게시글')),
            ],
            options={
                'verbose_name': '댓글',
                'verbose_name_plural': '댓글',
            },
        ),
    ]
