# Generated by Django 5.1.7 on 2025-03-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_image_post_latitude_post_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='마감일'),
        ),
    ]
