# Generated by Django 5.1.7 on 2025-03-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='enable_due_date',
            field=models.BooleanField(default=True, verbose_name='마감일 활성화'),
        ),
        migrations.AddField(
            model_name='category',
            name='enable_map',
            field=models.BooleanField(default=True, verbose_name='지도 활성화'),
        ),
        migrations.AlterField(
            model_name='post',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='마감일시'),
        ),
    ]
