# Generated by Django 5.1.7 on 2025-03-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category_enable_due_date_category_enable_map_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='enable_photo',
            field=models.BooleanField(default=True, verbose_name='사진 활성화'),
        ),
        migrations.AddField(
            model_name='category',
            name='enable_time',
            field=models.BooleanField(default=True, verbose_name='시간 활성화'),
        ),
    ]
