# Generated by Django 5.1.7 on 2025-03-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='enable_price',
            field=models.BooleanField(default=True, verbose_name='가격 활성화'),
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='가격'),
        ),
    ]
