# Generated by Django 5.1.7 on 2025-03-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_category_enable_price_post_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='related_posts',
            field=models.ManyToManyField(blank=True, related_name='tagged_by', to='blog.post', verbose_name='관련 게시글'),
        ),
    ]
