# Generated by Django 5.1.7 on 2025-03-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_tag_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='enable_tags',
            field=models.BooleanField(default=True, verbose_name='태그 활성화'),
        ),
    ]
